import Weapon from 'src/models/weapon';

const weaponsCatalogue: Weapon[] = [
	{
		name: 'Armalite 44',
		type: 'Pistol',
		damage: '4D6+1',
		range: 50,
		ROF: 1,
		shots: 8,
		ammo: '(12mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 450
	},
	{
		name: 'Astra Style-6',
		type: 'Pistol',
		damage: '1d6',
		range: 50,
		ROF: 2,
		shots: 6,
		ammo: '(5mm)',
		concealability: 'Pocket',
		accuracy: -1,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 75
	},
	{
		name: 'BudgetArms Auto 3',
		type: 'Pistol',
		damage: '3D6',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(11mm)',
		concealability: 'Jacket',
		accuracy: -1,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 350
	},
	{
		name: 'BudgetArms C-13',
		type: 'Pistol',
		damage: '1D6',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(5mm)',
		concealability: 'Pocket',
		accuracy: -1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 75
	},
	{
		name: 'BudgetArms Laser-Niner',
		type: 'Pistol',
		damage: '2D6+1',
		range: 50,
		ROF: 1,
		shots: 15,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 675
	},
	{
		name: 'Colt .38 Detective',
		type: 'Pistol',
		damage: '1d6+2',
		range: 50,
		ROF: 1,
		shots: 6,
		ammo: '(.38)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 200
	},
	{
		name: 'Colt AMT Model 2000',
		type: 'Pistol',
		damage: '4D6+1',
		range: 50,
		ROF: 1,
		shots: 8,
		ammo: '(12mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 500
	},
	{
		name: 'Colt Alpha-Omega',
		type: 'Pistol',
		damage: '2D6+2',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(.45 ACCP)',
		concealability: 'Jacket',
		accuracy: 2,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 500
	},
	{
		name: 'Dai Lung Cybermag 15',
		type: 'Pistol',
		damage: '1D6+1',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(6mm)',
		concealability: 'Pocket',
		accuracy: -1,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'C',
		cost: 50
	},
	{
		name: 'Dai Lung Streemaster',
		type: 'Pistol',
		damage: '2D6+3',
		range: 50,
		ROF: 2,
		shots: 12,
		ammo: '(10mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 250
	},
	{
		name: 'Federated Arms .22',
		type: 'Pistol',
		damage: '1d6',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(.22)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 50
	},
	{
		name: 'Federated Arms Impact',
		type: 'Pistol',
		damage: '1d6',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(.22)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 60
	},
	{
		name: 'Federated Arms X-22',
		type: 'Pistol',
		damage: '1D6+1',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(6mm)',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 150
	},
	{
		name: 'Federated Arms X-38',
		type: 'Pistol',
		damage: '2d6',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(.38)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 35
	},
	{
		name: 'Federated Arms X-9mm',
		type: 'Pistol',
		damage: '2D6+1',
		range: 50,
		ROF: 2,
		shots: 12,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 300
	},
	{
		name: 'Glock Thirty MP',
		type: 'Pistol',
		damage: '2d6+3',
		range: 50,
		ROF: 1,
		shots: 20,
		ammo: '(10mm)',
		concealability: 'Jacket',
		accuracy: 2,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 705
	},
	{
		name: 'Goncz-Tauras Pistol',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 15,
		ammo: '(8mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 200
	},
	{
		name: 'H&K P-11',
		type: 'Pistol',
		damage: '4d6+1',
		range: 50,
		ROF: 1,
		shots: 5,
		ammo: '(6mmRkt)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 700
	},
	{
		name: 'Malorian Arms Silver Gun',
		type: 'Pistol',
		damage: '2x2cm',
		range: 50,
		ROF: 2,
		shots: 7,
		ammo: 'frags',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'P',
		cost: 375
	},
	{
		name: 'Militech Arms Avenger',
		type: 'Pistol',
		damage: '2D6+1',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 250
	},
	{
		name: 'Sternmeyer Type 35',
		type: 'Pistol',
		damage: '3D6',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(11mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 400
	},
	{
		name: 'Towa 12 Polic Pistol',
		type: 'Pistol',
		damage: '1d6+1',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(6mm)',
		concealability: 'Jacket',
		accuracy: 3,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 450
	},
	{
		name: 'Goncz-Taurus MP',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 15,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: -1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 675
	},
	{
		name: 'Fashion Gun 9',
		type: 'Pistol',
		damage: '2d6+1',
		range: 25,
		ROF: 2,
		shots: 7,
		ammo: '(9mm)',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 40
	},
	{
		name: 'Generic Wondernine',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 14,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 240
	},
	{
		name: 'Beretta M97P',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 18,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 2,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 480
	},
	{
		name: 'CCMMC Goaxing CM-3',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 75
	},
	{
		name: 'Kang Tao Type 97',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 35
	},
	{
		name: 'Sci Fi Starrior 4',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 12,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 60
	},
	{
		name: 'Teen Dreem',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: -1,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'E',
		cost: 36
	},
	{
		name: 'Texas Arms 351 Gyrojet',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(9mm Gyro)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'C',
		cost: 420
	},
	{
		name: 'Calico Assault Pistol',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 2,
		shots: 50,
		ammo: '(9mm C)',
		concealability: 'Long Coat',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 450
	},
	{
		name: 'Beretta Plas 9 Fashion',
		type: 'Pistol',
		damage: '2d6+1',
		range: 50,
		ROF: 1,
		shots: 10,
		ammo: '(9mm)',
		concealability: 'Pocket',
		accuracy: -1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 200
	},
	{
		name: 'Uzi Miniauto 9',
		type: 'SMG',
		damage: '2D6+1',
		range: 150,
		ROF: 35,
		shots: 30,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 475
	},
	{
		name: 'H&K MP-2013',
		type: 'SMG',
		damage: '2D6+3',
		range: 150,
		ROF: 32,
		shots: 35,
		ammo: '(10mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 450
	},
	{
		name: 'Fed. Arms Tech Assault II',
		type: 'SMG',
		damage: '1D6+1',
		range: 150,
		ROF: 25,
		shots: 50,
		ammo: '(6mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 400
	},
	{
		name: 'Araska Minami 10',
		type: 'SMG',
		damage: '2D6+3',
		range: 200,
		ROF: 20,
		shots: 40,
		ammo: '(10mm)',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 500
	},
	{
		name: 'H&K MPK-9',
		type: 'SMG',
		damage: '2D6+1',
		range: 200,
		ROF: 25,
		shots: 35,
		ammo: '(9mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 520
	},
	{
		name: 'Sternmeyer SMG 21',
		type: 'SMG',
		damage: '3d6',
		range: 200,
		ROF: 15,
		shots: 30,
		ammo: '(11mm)',
		concealability: 'Long Coat',
		accuracy: -1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 500
	},
	{
		name: 'H&K MPK-11',
		type: 'SMG',
		damage: '4D6+1',
		range: 200,
		ROF: 20,
		shots: 30,
		ammo: '(12mm)',
		concealability: 'Long Coat',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 700
	},
	{
		name: 'Ingram MAC 14',
		type: 'SMG',
		damage: '4D6',
		range: 200,
		ROF: 10,
		shots: 20,
		ammo: '(12mm)',
		concealability: 'Long Coat',
		accuracy: -2,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 650
	},
	{
		name: 'Setsuko-Araska PMS Adv.',
		type: 'SMG',
		damage: '1d6+2',
		range: 200,
		ROF: 20,
		shots: 40,
		ammo: '(7mm)',
		concealability: 'Long Coat',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 1150
	},
	{
		name: 'Beretta M-24 Adv.SMG',
		type: 'SMG',
		damage: '2d6+1',
		range: 200,
		ROF: 25,
		shots: 50,
		ammo: '(8mm)',
		concealability: 'Long Coat',
		accuracy: 2,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 1250
	},
	{
		name: 'Malorian Arms Sub-Flechette',
		type: 'SMG',
		damage: '10mm',
		range: 100,
		ROF: 3,
		shots: 10,
		ammo: 'Flech',
		concealability: 'Jacket',
		accuracy: 2,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 795
	},
	{
		name: 'Militech Mini-Gat',
		type: 'SMG',
		damage: '1d6',
		range: 100,
		ROF: 40,
		shots: 120,
		ammo: '(.22C)',
		concealability: 'Long Coat',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 695
	},
	{
		name: 'Militech-10 SMG',
		type: 'SMG',
		damage: '2d6+3',
		range: 100,
		ROF: 20,
		shots: 30,
		ammo: '(10mm)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 455
	},
	{
		name: 'Militech-10 SMG',
		type: 'SMG',
		damage: '2d6+2',
		range: 100,
		ROF: 20,
		shots: 30,
		ammo: '(.45)',
		concealability: 'Jacket',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 455
	},
	{
		name: 'Militech Ronin Light Assault',
		type: 'Rifle',
		damage: '5D6',
		range: 400,
		ROF: 30,
		shots: 35,
		ammo: '(5.56)',
		concealability: 'None',
		accuracy: 1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 450
	},
	{
		name: 'AKR-20 Medium Assault',
		type: 'Rifle',
		damage: '5D6',
		range: 400,
		ROF: 30,
		shots: 30,
		ammo: '(5.56)',
		concealability: 'None',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 500
	},
	{
		name: 'FN-RAL Heavy Assault Rifle',
		type: 'Rifle',
		damage: '6D6+2',
		range: 400,
		ROF: 20,
		shots: 30,
		ammo: '(7.62)',
		concealability: 'None',
		accuracy: -1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 600
	},
	{
		name: 'Kalishnikov A-80 Hvy. Rifle',
		type: 'Rifle',
		damage: '6D6+2',
		range: 400,
		ROF: 25,
		shots: 35,
		ammo: '(7.62)',
		concealability: 'None',
		accuracy: -1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'E',
		cost: 550
	},
	{
		name: 'Militech Elect. LaserCannon',
		type: 'Rifle',
		damage: '1-5d6',
		range: 200,
		ROF: 2,
		shots: 10,
		ammo: '',
		concealability: 'None',
		accuracy: 2,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'R',
		cost: 8000
	},
	{
		name: 'Tsunami Arms Ramjet',
		type: 'Rifle',
		damage: '5d6+3-7d6+3',
		range: 800,
		ROF: 3,
		shots: 9,
		ammo: '',
		concealability: 'None',
		accuracy: 3,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 1230
	},
	{
		name: 'Polymer One-Shot Cannon',
		type: 'Rifle',
		damage: '4d6+2',
		range: 100,
		ROF: 1,
		shots: 1,
		ammo: '(13mm)',
		concealability: 'Long Coat',
		accuracy: -2,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'C',
		cost: 90
	},
	{
		name: 'Militech Cyborg Rifle',
		type: 'Rifle',
		damage: '7d6+3AP',
		range: 500,
		ROF: 2,
		shots: 30,
		ammo: '(.300WM)',
		concealability: 'None',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 800
	},
	{
		name: 'Pursuit Security Webgun',
		type: 'Rifle',
		damage: 'Entangle',
		range: 30,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'None',
		accuracy: 1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 250
	},
	{
		name: 'Underbarrel Capacitor Laser',
		type: 'Rifle',
		damage: '3d6',
		range: 25,
		ROF: 2,
		shots: 2,
		ammo: '',
		concealability: 'NA',
		accuracy: 2,
		reliability: 'UR',
		armorPeircing: '',
		availability: 'R',
		cost: 950
	},
	{
		name: 'Techtronica M40 Pulse Rifle',
		type: 'Rifle',
		damage: 'EMP',
		range: 50,
		ROF: 0.5,
		shots: 6,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 3500
	},
	{
		name: 'Militech M-31a1 AICW',
		type: 'Rifle',
		damage: '4d6',
		range: 200,
		ROF: 30,
		shots: 150,
		ammo: '(4.5mm)',
		concealability: 'None',
		accuracy: 2,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 1695
	},
	{
		name: 'Darra-Polytechnic M-9 AR',
		type: 'Rifle',
		damage: '4d6+2',
		range: 200,
		ROF: 25,
		shots: 40,
		ammo: '(5.5mm)',
		concealability: 'None',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 300
	},
	{
		name: 'Federated Arms Light Assault 15',
		type: 'Rifle',
		damage: '5d6',
		range: 200,
		ROF: 25,
		shots: 30,
		ammo: '(7mmC)',
		concealability: 'None',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 400
	},
	{
		name: 'Stein & Wasserman Model F',
		type: 'Rifle',
		damage: '(13mm)',
		range: 200,
		ROF: 1,
		shots: 8,
		ammo: '',
		concealability: 'Long Coat',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 1650
	},
	{
		name: 'Araska Rapid Assault 12',
		type: 'Shotgun',
		damage: '4D6',
		range: 50,
		ROF: 10,
		shots: 20,
		ammo: '',
		concealability: 'None',
		accuracy: -1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 900
	},
	{
		name: 'Sternmeyer Stakeout 10',
		type: 'Shotgun',
		damage: '4D6',
		range: 50,
		ROF: 2,
		shots: 10,
		ammo: '',
		concealability: 'None',
		accuracy: -2,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 450
	},
	{
		name: 'Militech Crusher SSG',
		type: 'Shotgun',
		damage: '3D6',
		range: 50,
		ROF: 2,
		shots: 6,
		ammo: '(20ga)',
		concealability: 'Jacket',
		accuracy: -1,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 450
	},
	{
		name: 'Luigi Franchi King Buck',
		type: 'Shotgun',
		damage: '6d6-4d6',
		range: 50,
		ROF: 2,
		shots: 4,
		ammo: '',
		concealability: 'None',
		accuracy: -1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 800
	},
	{
		name: 'Militech Military Shotgun',
		type: 'Shotgun',
		damage: '4d6',
		range: 50,
		ROF: 2,
		shots: 8,
		ammo: '(12ga)',
		concealability: 'None',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 300
	},
	{
		name: 'Barret-Arasaka Light 20mm',
		type: 'Heavy',
		damage: '4D10',
		range: 450,
		ROF: 1,
		shots: 10,
		ammo: '(20mm)',
		concealability: 'None',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'R',
		cost: 2000
	},
	{
		name: 'Scorpion 16 Missile Launcher',
		type: 'Heavy',
		damage: '7D10',
		range: 1000,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'None',
		accuracy: -1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'R',
		cost: 3000
	},
	{
		name: 'Militech Arms RPG-A',
		type: 'Heavy',
		damage: '6D10',
		range: 1000,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'None',
		accuracy: -2,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'R',
		cost: 1500
	},
	{
		name: 'K-A F-253 Flamethrower',
		type: 'Heavy',
		damage: '2D10',
		range: 50,
		ROF: 1,
		shots: 10,
		ammo: '',
		concealability: 'None',
		accuracy: -2,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 1500
	},
	{
		name: 'Rhinemetall EMG-85 Railgun',
		type: 'Heavy',
		damage: '5d10+10',
		range: 1500,
		ROF: 0.5,
		shots: 5,
		ammo: '(EAP)',
		concealability: 'None',
		accuracy: 3,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 11370
	},
	{
		name: 'Militech AM-3 AntiMatter',
		type: 'Heavy',
		damage: '6d10+2',
		range: 1600,
		ROF: 1,
		shots: 5,
		ammo: '(30mmEHI)',
		concealability: 'None',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 6000
	},
	{
		name: 'Militech Urban Missile Launch.',
		type: 'Heavy',
		damage: '4d6',
		range: 200,
		ROF: 2,
		shots: 12,
		ammo: '(MicroMiss)',
		concealability: 'Long Coat',
		accuracy: 2,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 900
	},
	{
		name: 'Club',
		type: 'Melee',
		damage: '1D6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 0
	},
	{
		name: 'Knife',
		type: 'Melee',
		damage: '1D6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 10
	},
	{
		name: 'Sword',
		type: 'Melee',
		damage: '2D6+2',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 100
	},
	{
		name: 'Axe',
		type: 'Melee',
		damage: '2D6+3',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 20
	},
	{
		name: 'Nunchaku/Tonfa',
		type: 'Melee',
		damage: '3D6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Long Coat',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 15
	},
	{
		name: 'Naginata',
		type: 'Melee',
		damage: '3D6',
		range: 2,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'P',
		cost: 100
	},
	{
		name: 'Shiriken',
		type: 'Melee',
		damage: '1D6/3',
		range: null,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 3
	},
	{
		name: 'Brass Knuckles',
		type: 'Melee',
		damage: '1D6+2',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 10
	},
	{
		name: 'Switchblade',
		type: 'Melee',
		damage: '1D6/2',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'NA',
		armorPeircing: '',
		availability: 'C',
		cost: 15
	},
	{
		name: 'Imi Chainknife',
		type: 'Melee',
		damage: '2d6+1',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 120
	},
	{
		name: 'Slamdance Inc. Spawnblade',
		type: 'Melee',
		damage: '1d6+BOD',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 450
	},
	{
		name: 'Kendachi Monowhip',
		type: 'Melee',
		damage: '2d6',
		range: 3,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 350
	},
	{
		name: 'Mystic Technologies',
		type: 'Melee',
		damage: '1d6',
		range: 5,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'C',
		cost: 125
	},
	{
		name: 'Dynatech Industries Hand Taser',
		type: 'Exotic',
		damage: 'Stun',
		range: 0,
		ROF: 1,
		shots: 12,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 50
	},
	{
		name: 'EagleTech Tomcat C-Bow',
		type: 'Exotic',
		damage: '4d6',
		range: 150,
		ROF: 1,
		shots: 12,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 150
	},
	{
		name: 'EagleTech Stryker X-Bow',
		type: 'Exotic',
		damage: '3d6+3',
		range: 50,
		ROF: 1,
		shots: 12,
		ammo: '',
		concealability: 'NA',
		accuracy: -1,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'C',
		cost: 220
	},
	{
		name: 'Underbarrel Microwaver',
		type: 'Exotic',
		damage: '1d6',
		range: 20,
		ROF: 2,
		shots: 4,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'P',
		cost: 500
	},
	{
		name: 'Scratchers',
		type: 'Melee',
		damage: '1d3',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 100
	},
	{
		name: 'Vampires',
		type: 'Melee',
		damage: '1d2',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'E',
		cost: 200
	},
	{
		name: 'Ripper',
		type: 'Melee',
		damage: '1d6+3',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: 'Knife',
		availability: '',
		cost: 400
	},
	{
		name: 'Wolvers',
		type: 'Melee',
		damage: '3d6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: 'Knife',
		availability: '',
		cost: 600
	},
	{
		name: 'Big Knucks',
		type: 'Melee',
		damage: '1d6+2',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: 500
	},
	{
		name: "Slice N' Dice",
		type: 'Melee',
		damage: '2d6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: 700
	},
	{
		name: 'Cybersnake',
		type: 'Melee',
		damage: '1d6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: 1200
	},
	{
		name: 'Hammer Hand',
		type: 'Melee',
		damage: '1d10',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: 600
	},
	{
		name: 'Buzz Hand',
		type: 'Melee',
		damage: '2d6+2',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: 600
	},
	{
		name: 'Spike Hand',
		type: 'Melee',
		damage: '1d6+3',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: 'Normal',
		availability: '',
		cost: 500
	},
	{
		name: 'Talon Foot',
		type: 'Melee',
		damage: '1d6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: 'Knife',
		availability: '',
		cost: 600
	},
	{
		name: 'Spike Heal Foot',
		type: 'Melee',
		damage: '2d6',
		range: 1,
		ROF: null,
		shots: null,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: 'Normal',
		availability: '',
		cost: 500
	},
	{
		name: 'Grenade Launcher',
		type: 'Heavy',
		damage: '*Grenade*',
		range: 225,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'None',
		accuracy: 0,
		reliability: 'ST',
		armorPeircing: '',
		availability: 'R',
		cost: 150
	},
	{
		name: 'Frag Grenade',
		type: 'Heavy',
		damage: '7d6',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Incediary Grenade',
		type: 'Heavy',
		damage: '4d3 3 Turns',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Stun Grenade',
		type: 'Heavy',
		damage: '-5 to Stun',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Dazzle Grenade',
		type: 'Heavy',
		damage: 'Blind 4 turns',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Sonic Grenade',
		type: 'Heavy',
		damage: 'Deaf 4 turns',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Mine',
		type: 'Heavy',
		damage: '4d10',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Jacket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 350
	},
	{
		name: 'C-6 Plstic Explosive',
		type: 'Heavy',
		damage: '8d10',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 100
	},
	{
		name: 'Cyberware Flamethrower',
		type: 'Heavy',
		damage: '2d6, 1d3 2T',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'NA',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: null
	},
	{
		name: 'Nausea Gas Grenade',
		type: 'Heavy',
		damage: '-4 Ref',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Tear Gas Grenade',
		type: 'Heavy',
		damage: '-2 Ref',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Sleep Gass Grenade',
		type: 'Heavy',
		damage: 'Drowsy, -2 Stats',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Biotoxin I Gas Grenade',
		type: 'Heavy',
		damage: '4d6',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Biotoxin II Gas Grenade',
		type: 'Heavy',
		damage: '8d6',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Nerve Gas Grenade',
		type: 'Heavy',
		damage: '8d10',
		range: null,
		ROF: 1,
		shots: 1,
		ammo: '',
		concealability: 'Pocket',
		accuracy: 0,
		reliability: 'VR',
		armorPeircing: '',
		availability: 'P',
		cost: 30
	},
	{
		name: 'Micromissile Launcher',
		type: 'Heavy',
		damage: '4d6',
		range: null,
		ROF: 1,
		shots: 4,
		ammo: '',
		concealability: 'None',
		accuracy: 2,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: null
	},
	{
		name: 'Capacitor Laser',
		type: 'Rifle',
		damage: '3d6 p.sec',
		range: 10,
		ROF: 1,
		shots: 2,
		ammo: '',
		concealability: 'None',
		accuracy: 3,
		reliability: 'VR',
		armorPeircing: '',
		availability: '',
		cost: null
	}
];

export default weaponsCatalogue;
