import Stats from './stats';

const skills = {
	'Personal Grooming': 'attractiveness',
	'Wardrobe & Style': 'attractiveness',
	Endurance: 'body',
	'Strength Feat': 'body',
	Swimming: 'body',

	Interrogation: 'cool',
	Oratory: 'cool',
	'Resist Torture/Drugs': 'cool',
	Streetwise: 'cool',

	'Human Perception': 'empathy',
	Interview: 'empathy',
	Leadership: 'empathy',
	Social: 'empathy',
	'Persuasion & Fast Talk': 'empathy',
	Perform: 'empathy',

	Accounting: 'inteligence',
	Anthropology: 'inteligence',
	'Awareness/Notice': 'inteligence',
	Biology: 'inteligence',
	Botany: 'inteligence',
	Chemistry: 'inteligence',
	Composition: 'inteligence',
	'Diagnose Illness': 'inteligence',
	'Education & General Knowledge': 'inteligence',
	Expert: 'inteligence',
	Gamble: 'inteligence',
	Geology: 'inteligence',
	'Hide/Evade': 'inteligence',
	History: 'inteligence',
	'Know Languages (Choose One)': 'inteligence',
	'Library Search': 'inteligence',
	Mathematics: 'inteligence',
	Physics: 'inteligence',
	Programming: 'inteligence',
	'Shadow/Track': 'inteligence',
	'Stock Market': 'inteligence',
	'System Knowledge': 'inteligence',
	Teaching: 'inteligence',
	Zoology: 'inteligence',

	Archery: 'reflex',
	Athletic: 'reflex',
	Brawling: 'reflex',
	Dance: 'reflex',
	'Dodge & Escape': 'reflex',
	Driving: 'reflex',
	Fencing: 'reflex',
	Handgun: 'reflex',
	'Heavy Weapons': 'reflex',
	'Martial Arts (Choose One)': 'reflex',
	Melee: 'reflex',
	Motorcycle: 'reflex',
	'Operate Heavy Machinery': 'reflex',
	'Pilot: Gyro': 'reflex',
	'Pilot: Fixed Wing': 'reflex',
	'Pilot: Dirigible': 'reflex',
	'Pilot: Vect. Thrust Vehicle': 'reflex',
	Rifle: 'reflex',
	Stealth: 'reflex',
	Submachinegun: 'reflex',

	'Aero Tech': 'tech',
	'AV Tech': 'tech',
	'Basic Tech': 'tech',
	'Cryotank Operation': 'tech',
	'Cyberdeck Design': 'tech',
	'Cyber Tech': 'tech',
	Demolitions: 'tech',
	Disguise: 'tech',
	Electronics: 'tech',
	'Elect. Security': 'tech',
	'First Aid': 'tech',
	Forgery: 'tech',
	'Gyro Tech': 'tech',
	'Paint or Draw': 'tech',
	'Photo & Film': 'tech',
	Pharmaceuticals: 'tech',
	'Pick Lock': 'tech',
	'Pick Pocket': 'tech',
	'Play Instrument': 'tech',
	Weaponsmith: 'tech'
};

export default skills;
